# Generated by Django 4.1.7 on 2023-03-28 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='foodcollection',
            new_name='place',
        ),
    ]
